### ISSUE TITLE
live interval splitting in register allocation pass

### ISSUE THREAD

**Issue by inolen** [inolen/dreavm#12]
Currently, live intervals are not split during register allocation. Instead, when we fail to allocate a register, the register belonging to the longest interval range is spilled to the stack forever.

This makes x64 emitting a lot more complicated. Many operations only work when the operand is in a register, resulting in a lot of code that's responsible for moving values from the stack to a temporary register and copying back when the operation is done. As I started working on backpatching code tonight, this gets even messier: now there is variable sized code to try and backpatch, or the code must be padded so the size is consistent.

Instead of spilling a variable permanently to the stack, if we always allocate a register for the value by splitting an existing live interval (adding synchronization points around the split as part of the register allocation pass), the amount of work each backend has to do when emitting would be greatly reduced.

**Comment by skmp** [comment]
On reicast I only kill spans, and never spill them to stack. I also assume all registers are on registers. A bit wasteful for x86/x64 with memory operands, but it doesn't really affect the speed. Thank intel for huge OoO engine!

For the backpacking you may want to do a call, so that you only have to patch the call destination. Calls are essentially for free on x86 and this will make the patching logic fairly trivial.

**Comment by inolen** [comment]
Finished with 1928ad76897a2f5abcfac49d97fb8f40ca65b710 and 38666680318561bb067e13e0cbf164065febc21f.

**Comment by skmp** [comment]
:+1: :+1:
