### ISSUE TITLE
x64 code caching

### ISSUE THREAD

**Issue by inolen** [inolen/dreavm#2]
Currently, the x64 backend allocates a large 32mb buffer and emits code there until everything explodes:
https://github.com/inolen/dreavm/blob/master/src/cpu/backend/x64/x64_backend.cc#L22

It'd be nice to dig into xbyak's custom allocator and figure out a way to manage, grow and shrink this buffer as blocks are created and destroyed.

**Comment by skmp** [comment]
Resizing the buffer will incur huge performance penalties, mostly because of cache effects. You'll also have to re-link all of your external calls. A realistic and simple scenario is to just clean up and start over, on nullDC I used to have some "garbage collection" pass that relocated only a few blocks at each pass to avoid the perfm. hit

**Comment by inolen** [comment]
Closed with https://github.com/inolen/dreavm/commit/6198f1bede8dd10dffbf9a8dcbd233b4deea5887.

Ended up adding a return status `enum AsmResult { ASM_SUCCESS, ASM_OVERFLOW };` to `backend::AssembleBlock`. When the backend overflows it's codegen buffer, it returns `ASM_OVERFLOW` at which point the runtime will reset the block cache and try again (erroring fatally if it can't emit on an empty buffer).

**Comment by skmp** [comment]
To simplify matters on reicast I require 64KB empty code upon compiling a block, and I cap max block size to 511 IL opcodes. Not the best approach, but simple enough
